### PR TITLE
Wait for a successful get of namespace during creation

### LINKED ISSUE #391: [Bug] Namespace creation fails with PermissionDenied on read-after-create when using Developer service account
**Description**

When creating a namespace with the Temporal Cloud Terraform provider (v1.1.1) using a Developer-role service account, the namespace is created successfully, but the provider immediately fails during the post-create read with:

`PermissionDenied: request unauthorized`

If the same identity waits ~50–60 seconds and retries GetNamespace, the read succeeds without any credential or permission changes.

This behavior does not occur when using an admin identity, which can read the namespace immediately after creation.

The failure happens inside the provider’s create path (read-after-create), so client-side workarounds such as time_sleep are not effective.

**Reproduction**

This can be reproduced outside Terraform using the Temporal Cloud CLI (tcld) with the same service account API key used by Terraform/Pulumi:

# Using a Developer-role service account API key
export TEMPORAL_CLOUD_API_KEY=...

`tcld namespace create --namespace test-baz --region us-east-1`

# Immediately after creation:
`tcld namespace get --namespace test-baz.<account-id>`
# → PermissionDenied: request unauthorized

# After ~50–60 seconds:
`tcld namespace get --namespace test-baz.<account-id>`
# → Success

Using an admin identity does not reproduce the issue; the read succeeds immediately.

Within the Terraform provider, the failure occurs during the immediate GetNamespace after CreateNamespace, without retry logic.

Relevant provider code path (no retry/backoff present):

https://github.com/temporalio/terraform-provider-temporalcloud/blob/c40357dbf63a9426c8edef1fbf5ad533eaf2d52d/internal/provider/namespace_resource.go#L463

**Environment / Versions**

Terraform provider: temporalio/temporalcloud v1.1.1
IaC tool: Terraform (via Pulumi)
Authentication: Service account API key
Service account role: Developer

**Additional context**

The same API key is used for both CreateNamespace and GetNamespace.

No role or permission changes occur during the delay window.

The namespace exists and becomes readable after ~50–60 seconds, indicating a permission propagation / read-after-create consistency delay for non-admin identities.

Client-side sleeps (e.g., time_sleep) are not effective because the failure occurs inside the provider’s create path before control returns to Terraform/Pulumi.

**Suggested provider improvement:**

After a successful CreateNamespace, retry GetNamespace when the error is PermissionDenied or NotFound, with backoff, for a bounded period (e.g., up to 180 seconds).
This retry logic should be scoped only to the create path, not to all read operations.

### PR DESCRIPTION
**Pull request by asmclean**
## What was changed
When creating a namespace, poll for a successful read of the namespace before returning.

## Why?
When a non-admin role is used in the creation of a namespace, there is a delay between creation of the namespace and successful authorization to the namespace.  For instance, if the provider is configured using a service account with a developer role, actions immediately following creation of a new namespace could fail.  This change ensures the namespace can be read before the creation is completed.

## Checklist

1. Closes https://github.com/temporalio/terraform-provider-temporalcloud/issues/391

2. How was this tested:
Tested using a SA with developer role against prod.  However, my first attempt failed due to the auth. propagation happening too quickly, so I tested using a build of the provider with the `client.AwaitAsyncOperation` on the `CreateNameSpace` removed.

4. Any docs updates needed?
No.

### CODE REVIEW

File: internal/provider/namespace_resource.go [hunk 1]
```diff
@@ -727,6 +725,96 @@ func (r *namespaceResource) ImportState(ctx context.Context, req resource.Import
 	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
 }
 
+// waitForNamespaceAvailableConfig contains configuration for polling behavior.
+type waitForNamespaceAvailableConfig struct {
+	initialDelay     time.Duration
+	retryInterval    time.Duration
+	maxRetryInterval time.Duration
+	maxAttempts      int
```
Comment (asmclean) [inline internal/provider/namespace_resource.go]: Using an initial value, exponential, and max might be overkill.  This could probably just a a set interval and max attempts.  If there's a preference for that, I can some of this.

File: internal/provider/namespace_resource.go [hunk 2]
```diff
@@ -727,6 +725,96 @@ func (r *namespaceResource) ImportState(ctx context.Context, req resource.Import
...
+			Namespace: namespaceID,
+		})
+
+		if err == nil {
+			tflog.Debug(ctx, "namespace successfully retrieved")
+			return ns.Namespace, nil
+		}
+
+		// Check if it's a PermissionDenied error that we should retry, or a different error we should fail on
+		if status.Code(err) == codes.PermissionDenied {
```
Comment (anekkanti) [inline internal/provider/namespace_resource.go]: [nit] Maybe keep polling for NotFound as well?

File: internal/provider/namespace_resource.go (hunk 1 above)
Comment (anekkanti) [reply internal/provider/namespace_resource.go]: I agree i think a polling freq and overall timeout should be good enough.

**Review by anekkanti — APPROVED** [review]
